"""Add foreign key to Course.instructor

Revision ID: 19831a1d7589
Revises: 618a5f936389
Create Date: 2025-05-12 05:42:35.494374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19831a1d7589'
down_revision = '618a5f936389'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_course_instructor_username',  # Add constraint name
            'users', 
            ['instructor'], 
            ['username']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint( 'fk_course_instructor_username',  
            type_='foreignkey')

    op.create_table('_alembic_tmp_registrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('semester_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'semester_id', name='_student_semester_uc')
    )
    # ### end Alembic commands ###
