"""Add unique constraint to Registration

Revision ID: 618a5f936389
Revises: 
Create Date: 2025-05-08 01:52:51.388210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618a5f936389'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_unique_constraint('_student_semester_uc', ['student_id', 'semester_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint('_student_semester_uc', type_='unique')

    # ### end Alembic commands ###
